### ISSUE TITLE
Calling envi with python script does not work

### ISSUE THREAD

**Issue by twosevenska** [twosevenska/envi#1]
If we try something like `envi python3 myscript.py` it fails since we are prolly only doing `eval $1`.

**Comment by geodimm** [comment]
Try replacing `eval "$1"` with `exec "$@"` 😛

**Comment by twosevenska** [comment]
Yep it works! Thanks for the suggestion :)

https://github.com/twosevenska/envi/commit/81984b8ca15d1febb30f335ce468604a346f4136
